# -*- coding: utf-8 -*-
"""internship3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yiWBbVtSyZ4TuMwEIMwh4qf5AZmzQMn9
"""

df = pd.read_csv("/content/Walmart Data Analysis and Forcasting.csv")
df.head()

df.isnull()

df.isnull().sum()

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Weekly_Sales',y='Holiday_Flag',palette='pastel')

plt.title('Boxplot of Holiday_Flag by Weekly_Sales Class',fontsize=16)
plt.xlabel('Weekly_Sales class',fontsize=12)
plt.ylabel('Holiday_Flag',fontsize=12)
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Temperature',y='CPI',palette='pastel')

plt.title('Boxplot of CPI by Temperature Class',fontsize=16)
plt.xlabel('Temperature class',fontsize=12)
plt.ylabel('CPI',fontsize=12)
plt.show()



import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

plt.figure(figsize=(10, 6))
sns.histplot(df['Weekly_Sales'], kde=True, bins=30)
plt.title('Distribution of Weekly Sales', fontsize=16)
plt.xlabel('Weekly Sales', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

plt.figure(figsize=(10, 6))
sns.histplot(df['Unemployment'], kde=True, bins=30)
plt.title('Distribution of Unemployment', fontsize=16)
plt.xlabel('Unemployment', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.show()

holiday_counts = df['Holiday_Flag'].value_counts()

plt.figure(figsize=(8, 8))
plt.pie(holiday_counts, labels=holiday_counts.index, autopct='%1.1f%%', startangle=90, colors=['skyblue', 'lightcoral'])
plt.title('Distribution of Holiday Flag', fontsize=16)
plt.ylabel('') # Hide the y-label for pie chart
plt.show()

import pandas as pd
df["Date"] = pd.to_datetime(df["Date"],dayfirst=True)
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day

df[["Date","Year","Month","Day"]].head()

df

from sklearn.preprocessing import MinMaxScaler,StandardScaler
daily_data=pd.read_csv('/content/Walmart Data Analysis and Forcasting.csv')

numerical_coloumns = ['Fuel_Price','CPI','Unemployment']
daily_data.dropna(subset=numerical_coloumns,inplace=True)
min_max_scaler=MinMaxScaler()
standard_scaler=StandardScaler()

daily_data['FuelPrice_Standard']=standard_scaler.fit_transform(daily_data[['Fuel_Price']])

daily_data['CPI_standard']=standard_scaler.fit_transform(daily_data[['CPI']])

daily_data['Unemployment_Standard']=standard_scaler.fit_transform(daily_data[['Unemployment']])

print(daily_data[['FuelPrice_Standard','CPI_standard','Unemployment_Standard']])

daily_data['Fuel_Price_MinMax']=min_max_scaler.fit_transform(daily_data[['Fuel_Price']])

daily_data['CPI_MinMax']=min_max_scaler.fit_transform(daily_data[['CPI']])

daily_data['Unemployment_MinMax']=min_max_scaler.fit_transform(daily_data[['Unemployment']])

print(daily_data[['Fuel_Price_MinMax','CPI_MinMax','Unemployment_MinMax']])

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Check for missing values
print("Missing Values:\n", df.isnull().sum())

# Summary statistics
print("\nSummary Statistics:\n", df.describe())

# Correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df.corr(numeric_only=True),
            annot=True,
            cmap="coolwarm",
            fmt=".2f",
            linewidths=0.5)

plt.title("Feature Correlation Heatmap")
plt.show()

# Pairplot for key variables
sns.pairplot(df[['Weekly_Sales',
                 'Temperature',
                 'Fuel_Price',
                 'CPI',
                 'Unemployment']])

plt.show()

# Distribution of target variable (Weekly_Sales)
plt.figure(figsize=(8, 5))
sns.histplot(df['Weekly_Sales'],
             bins=30,
             kde=True,
             color='blue')

plt.title("Distribution of Weekly Sales")
plt.xlabel("Weekly Sales")
plt.ylabel("Frequency")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

plt.figure(figsize=(8, 5))

sns.barplot(data=df, x='Year', y='Weekly_Sales', color='blue')

plt.title("Sales obtained in a week")

plt.xlabel("Year")

plt.ylabel("Weekly_Sales")

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

plt.figure(figsize=(8, 5))

sns.barplot(data=df, x='Day', y='Weekly_Sales', color='blue')

plt.title("Sales obtained in a week")

plt.xlabel("Day")

plt.ylabel("Weekly_Sales")

plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

plt.figure(figsize=(8, 5))

sns.barplot(data=df, x='Month', y='Weekly_Sales', color='blue')

plt.title("Sales obtained in a week")

plt.xlabel("Month")

plt.ylabel("Weekly_Sales")

plt.show()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Define features (X) and target (y)
X = df.drop(columns=["Weekly_Sales", "Date"])  # Dropping Weekly_Sales as it's the target and Date as it's not numerical
y = df["Weekly_Sales"]

# Split the dataset (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Model Evaluation
r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=y_pred, color='blue', alpha=0.7)
plt.xlabel("Actual Prices ")
plt.ylabel("Predicted Prices")
plt.title("Actual Prices vs. Predicted Prices")
plt.axline([0,0],[1,1],color="red",linestyle="--")
plt.show()

from scipy.stats import skew

import numpy as np
skewness = df.select_dtypes(include=np.number).skew()

num_cols=len(df.columns)
plt.figure(figsize=(15,num_cols*3))

for i,col in enumerate(df.columns):
  plt.subplot(num_cols,2,2*i+1)
  sns.histplot(df[col],kde=True)
  plt.title(f"Hisotogram of {col}")
  plt.subplot(num_cols,2,2*i+2)
  sns.boxplot(x=df[col])
  plt.title(f"Boxplot of {col}")

plt.tight_layout()
plt.show()

import numpy as np
skewness = df.select_dtypes(include=np.number).skew()
print(skewness)

import numpy as np

skewed_cols=df.select_dtypes(include=np.number).skew().abs()
highly_skewed=skewed_cols[skewed_cols>1].index
negatively_skewed=skewed_cols[skewed_cols< 1].index
print("Highly Skewed Columns:",highly_skewed)
print("Negatively Skewed Columns:",negatively_skewed)

df[highly_skewed]=df[highly_skewed].apply(lambda x:np.log1p(x))

from sklearn.preprocessing import PowerTransformer

pt=PowerTransformer(method='yeo-johnson')
df[negatively_skewed]=pt.fit_transform(df[negatively_skewed])

import numpy as np
df.select_dtypes(include=np.number).skew()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

X = df.drop(columns=["Weekly_Sales", "Date"])
y = df["Weekly_Sales"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
r2 = r2_score(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=y_pred, color='blue', alpha=0.7)
plt.xlabel("Actual Prices (medv)")
plt.ylabel("Predicted Prices (medv)")
plt.title("Actual Prices vs. Predicted Prices")
plt.axline([0,0],[1,1],color="red",linestyle="--")
plt.show()

from sklearn.ensemble import RandomForestRegressor

rf_model=RandomForestRegressor(n_estimators=100,random_state=42)
rf_model.fit(X_train,y_train)

y_pred=rf_model.predict(X_test)

r2=r2_score(y_test,y_pred)
rmse=mean_squared_error(y_test,y_pred)**0.5

print(f"R² Score: {r2:.4f}")
print(f"RMSE: {rmse:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(8, 6))
sns.scatterplot(x=y_test, y=y_pred, color='blue', alpha=0.7)
plt.xlabel("Actual  weekly Sale (medv)")
plt.ylabel("Predicted weekly sale (medv)")
plt.title("Actual  vs. Predicted ")
plt.axline([0,0],[1,1],color="red",linestyle="--")
plt.show()

df

import pandas as pd
import numpy as np

Store = 3
Date = '10-12-2014'
Holiday_Flag = 0
Temperature = 50.41
Fuel_Price = 3.701
CPI = 300.096358
Unemployment = 7.106
input_data = {
    'Store': [Store],
    'Date': [Date],
    'Holiday_Flag': [Holiday_Flag],
    'Temperature': [Temperature],
    'Fuel_Price': [Fuel_Price],
    'CPI': [CPI],
    'Unemployment': [Unemployment]
}
sample_df = pd.DataFrame(input_data)
print("Original Sample Data:")
display(sample_df)

sample_df["Date"] = pd.to_datetime(sample_df["Date"])
sample_df["Year"] = sample_df["Date"].dt.year
sample_df["Month"] = sample_df["Date"].dt.month
sample_df["Day"] = sample_df["Date"].dt.day
sample_df = sample_df.drop(['Date'],axis=1)

prediction = rf_model.predict(sample_df)
print(f"Predicted Class: {prediction[0]}")