# -*- coding: utf-8 -*-
"""intershipday1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUYQERxvQ7xsFutVYmZUUucXGAlpvgq3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/titanic uncleaned.csv")

df



df.head()

df.tail()

df.head(10)

df.info()

df.shape

df.dtypes

df.describe()

df['Age']

df.isnull()

df.isnull().sum()

df['Age_mean_imputed']=df['Age'].fillna(df['Age'].mean())
df['Age_median_imputed']=df['Age'].fillna(df['Age'].median())
df['Cabin_mode_imputed']=df['Cabin'].fillna(df['Cabin'].mode()[0])
df[['Age','Age_mean_imputed','Age_median_imputed','Cabin','Cabin_mode_imputed']]

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Pclass',y='Age',palette='pastel')

plt.title('Boxplot of Age by Passenger Class',fontsize=16)
plt.xlabel('Passenger class',fontsize=12)
plt.ylabel('age',fontsize=12)
plt.show()

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Pclass',y='Survived',palette='pastel')

plt.title('Boxplot of Survived by Passenger Class',fontsize=16)
plt.xlabel('Passenger class',fontsize=12)
plt.ylabel('Survived',fontsize=12)
plt.show()

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.boxplot(data=df,x='Embarked',y='Fare',palette='pastel')

plt.title('Boxplot of Fare by Embarked Class',fontsize=16)
plt.xlabel('Embarked class',fontsize=12)
plt.ylabel('fare',fontsize=12)
plt.show()

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Re-load df for this cell to ensure it's defined,
# especially if this cell is run in isolation or after a kernel restart.
df = pd.read_csv("/content/titanic uncleaned.csv")

encoded_data=df.copy()

label_encoder=LabelEncoder()
encoded_data['Sex']=label_encoder.fit_transform(encoded_data['Sex'])

one_hot_encoded=pd.get_dummies(encoded_data['Embarked'],prefix='Embarked')
encoded_data=pd.concat([encoded_data,one_hot_encoded],axis=1)

pclass_mapping={1:'First',2:'Second',3:'Third'}
encoded_data['Pclass']=encoded_data['Pclass'].map(pclass_mapping)

# 'Sex_Label' was not created in this cell, so it has been removed from the print statement.
# The 'Sex' column now contains the label-encoded numerical values.
print(encoded_data[['Sex','Embarked','Embarked_Q','Embarked_S','Embarked_C','Pclass']])